### ISSUE TITLE
client.lua:203 attempt to index a nil value (field 'job')

### ISSUE THREAD

**Issue by B0biD0ng** [Z3rio/zerio-proximityprompts#1]
![image](https://user-images.githubusercontent.com/81963237/181724676-61516593-0d6e-47e8-9d3a-b4880012fb04.png)
Hello, I uploaded your script because we bought zerio-boosmena from you and an error was created in the script zerio-proximityprompt/client.lua:203
Could you please help?

**Comment by Z3rio** [comment]
Open a ticket in my discord instead.
http://discord.zerio-scripts.com

**Comment by Z3rio** [comment]
Fixed
